#! /bin/bash

# Outputs the memory usage of the given user.  Defaults to the current user.
# Usage: memory [username]

USER=${1:-`whoami`}
ps -u $USER -o rss,command | awk 'index($0, "apache2-mpm-peruser")==0 {print $0;sum+=$1} END {printf("Total %iM\n", sum / 1024)}'